### ISSUE TITLE
Render results on dtu dataset.

### ISSUE THREAD

**Issue by Wuuu3511** [hugoycj/2dgs-gaustudio#1]
Thank you for sharing the code.

I tested the code on dtu scan24. Using the script "python train.py -s <path to data> -m output/trained_result"

It seems there are some issues with the rendering images. The scene appears as if observed through a piece of "blue transparent glass."

<img width="640" alt="image" src="https://github.com/hugoycj/2dgs-gaustudio/assets/107132698/53b2fb10-4084-44dc-b1d2-23833e3647af">

I'm unable to determine what might be causing this issue，but the rendering results of the mesh seem to be correct.

![image](https://github.com/hugoycj/2dgs-gaustudio/assets/107132698/47eabcf8-6b2c-4794-8b8a-bf38bb554c18)

This is the data I generated using COLMAP（https://drive.google.com/file/d/1Kz_zeUbYWMPxnF1mhoLbVJkj7XBt2KpA/view?usp=sharing. I would greatly appreciate it if you could help me solve this problem.

**Comment by hugoycj** [comment]
Thanks for the feedback! The current code is from our private implementation, and we haven't had the bandwidth to thoroughly test it yet. There are likely some critical issues in the current code that need addressing. 

I'll look into it as soon as I can to get those fixes implemented.

**Comment by hugoycj** [comment]
![Snipaste_2024-04-16_15-56-13](https://github.com/hugoycj/2dgs-gaustudio/assets/40767265/5b3f45c8-f3de-4b5f-b042-bd3b61f4f322)
The issue caused by the GauStudio's colmap initializer has been resolved. You can now pull and install the latest GauStudio version to fix the error. However, the quality of the extracted mesh is not satisfactory. Some parameters may need to be tuned, and the original distortion loss function and 2DGS rasterization should be implemented to improve the mesh quality. 

We sincerely welcome any PR to further improve this implementation.

**Comment by hugoycj** [comment]
<img width="447" alt="image" src="https://github.com/hugoycj/2dgs-gaustudio/assets/40767265/b28fe4a5-d0b2-410f-a1fb-f06ecbafe396">

We have updated the parameters to get a more detailed mesh.

**Comment by KKjiaming** [comment]
hi, i want to kindly ask, have you test the Chamfer distance of dtu dataset, the extarct mesh might has a shift with gt.

**Comment by KKjiaming** [comment]
> <img alt="image" width="447" src="https://private-user-images.githubusercontent.com/40767265/323444378-b28fe4a5-d0b2-410f-a1fb-f06ecbafe396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTE3OTQsIm5iZiI6MTcxNDExMTQ5NCwicGF0aCI6Ii80MDc2NzI2NS8zMjM0NDQzNzgtYjI4ZmU0YTUtZDBiMi00MTBmLWExZmItZjA2ZWNiYWZlMzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA2MDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMTc1ZWRhZDNhOGVlNThhZGU3ZmRlODMyM2QyNmJlODc2ZDI4ZDlhZWFlNmM1NGJkMDExMjRiYmZlMDU5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zUq_nYIAzrzqbGJ1bkx7jm-fYlnDX6p-qk31ZKuXnlM">
> We have updated the parameters to get a more detailed mesh.

hi, i want to kindly ask, have you test the Chamfer distance of dtu dataset, the extarct mesh might has a shift with gt.
