### ISSUE TITLE
Confused about the results

### ISSUE THREAD

**Issue by lif314** [hugoycj/2dgs-gaustudio#3]
I tested on Tandt/Truck, and the results were not satisfactory. the 'gaussian' is not a 'disk' like in 2DGS. It has values for all three scales.

Gaussian Balls:
![image](https://github.com/hugoycj/2dgs-gaustudio/assets/63114150/e2255137-0c00-4468-ac3d-7cfce35b720e)

Mesh:
![image](https://github.com/hugoycj/2dgs-gaustudio/assets/63114150/e9757ddf-2dd9-4930-b00d-f39900e27be3)

**Comment by hugoycj** [comment]
That's an interesting issue with the visualization. We've checked the scaling of the trained model and confirmed that the third axes are all 0. That suggests the problem may lie in the visualization process itself.

<img width="453" alt="image" src="https://github.com/hugoycj/2dgs-gaustudio/assets/40767265/41875edc-3f88-4079-b25e-ee8ede49710a">

Maybe we need to dig into SIBR_viewer source code to identify any issues or inconsistencies in how the visualization is being generated.

**Comment by lif314** [comment]
> That's an interesting issue with the visualization. We've checked the scaling of the trained model and confirmed that the third axes are all 0. That suggests the problem may lie in the visualization process itself.
> 
> <img alt="image" width="453" src="https://private-user-images.githubusercontent.com/40767265/323089476-41875edc-3f88-4079-b25e-ee8ede49710a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDA0NzQsIm5iZiI6MTcxMzM0MDE3NCwicGF0aCI6Ii80MDc2NzI2NS8zMjMwODk0NzYtNDE4NzVlZGMtM2Y4OC00MDc5LWIyNWUtZWU4ZWRlNDk3MTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3NDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxOGNkYzQ0Y2UzOWU0YjRhMTE3NDYzNTJlMzA2YTU0YTMyZmNhMWI4Njg4NjE5MzcyMjM4ZjM5N2U4YzkxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gTrM08qujNlhbUHDAx9nOodptYjS1M8-fy94hXW2QqU">
> Maybe we need to dig into SIBR_viewer source code to identify any issues or inconsistencies in how the visualization is being generated.
There is nothing wrong with your code. It was my carelessness that caused this issue. I use [GaussianSplattingView](https://github.com/limacv/GaussianSplattingViewer) to visualize Gaussians, this problem should be a bug of GaussianSplattingView. I'm sorry for wasting your time with this issue! Thanks for your great work, I will close this issue.

![image](https://github.com/hugoycj/2dgs-gaustudio/assets/63114150/a9b72cd6-7224-4cbf-a006-3959208bf5ae)
